### ISSUE TITLE
[FEATURE] Add Candidate 

### ISSUE THREAD

**Issue by AbdelrahmanBadwy** [Minashehata11/VotingSystem#1]
# Tasks
- [x] Add the old work
- [x] Connect to the db
- [x] Test the code

# Resources
https://learn.microsoft.com/en-us/dotnet/
